### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Jeremyop** [clausemaven/Maven-Telegram-AIO-Scrapper-and-Adder#2]
Do you have discord?

**Comment by Jeremyop** [comment]
Traceback (most recent call last):
  File "C:\Users\Op\Desktop\Maven-Telegram-AIO-Scrapper-and-Adder-main\Maven.py", line 104, in <module>
    client = TelegramClient(f"../sessions/{phone}", api_id, api_hash)
  File "C:\Users\Op\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\telegrambaseclient.py", line 273, in __init__
    session = SQLiteSession(session)
  File "C:\Users\Op\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\sessions\sqlite.py", line 47, in __init__
    c = self._cursor()
  File "C:\Users\Op\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\sessions\sqlite.py", line 228, in _cursor
    self._conn = sqlite3.connect(self.filename,
sqlite3.OperationalError: unable to open database file

**Comment by baramhs** [comment]
> Traceback (most recent call last): File "C:\Users\Op\Desktop\Maven-Telegram-AIO-Scrapper-and-Adder-main\Maven.py", line 104, in client = TelegramClient(f"../sessions/{phone}", api_id, api_hash) File "C:\Users\Op\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\telegrambaseclient.py", line 273, in **init** session = SQLiteSession(session) File "C:\Users\Op\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\sessions\sqlite.py", line 47, in **init** c = self._cursor() File "C:\Users\Op\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\sessions\sqlite.py", line 228, in _cursor self._conn = sqlite3.connect(self.filename, sqlite3.OperationalError: unable to open database file

same problem , already tell him , but he say it fixed

**Comment by clausemaven** [comment]
I was hooked up with work, I did fix it but couldn't commit changes. I'll commit changes after writing this. Really sorry for the inconvenience. Make sure to re download :)

**Comment by clausemaven** [comment]
Please run it and tell me if the issue has been fixed, cheers!:)

**Comment by clausemaven** [comment]
Closed due to inactivity
